### ISSUE TITLE
Press "comments" issue, validation controller is called

### ISSUE THREAD

**Issue by NebesnyiA** [SeredaYehor/FaceSpam_social_media#33]
If you press "comments" button under the first post, it will call validation controller
![изображение](https://user-images.githubusercontent.com/73758238/166143513-e2145b23-ff80-426b-9be1-8abe114105aa.png)
Result:
![изображение](https://user-images.githubusercontent.com/73758238/166143520-74934096-b3c8-463f-8fa4-afc1954345c6.png)

**Comment by SeredaYehor** [comment]
Based

**Comment by SeredaYehor** [comment]
Remove html.beginform() function from main.cshtml
