### ISSUE TITLE
Press "Main" on navigation panel (all forms), null reference exeption

### ISSUE THREAD

**Issue by NebesnyiA** [SeredaYehor/FaceSpam_social_media#34]
If you press "Main" button on navigation panel, null reference exeption will be catched.
![изображение](https://user-images.githubusercontent.com/73758238/166143626-7ef796ab-b659-4246-95d6-5a4943e2d5b7.png)

**Comment by SeredaYehor** [comment]
Remove everything except return in IActionResult Main()

**Comment by SeredaYehor** [comment]
Closing issue
